force-app/main/default/objects/Country_Name__mdt/Country_Name__mdt.object-meta.xml
<CustomObject>
    <label>Country Name</label>
    <pluralLabel>Country Names</pluralLabel>
</CustomObject>

force-app/main/default/objects/Country_Name__mdt/fields/Continent_Name__c.field-meta.xml
<CustomField>
    <fullName>Continent_Name__c</fullName>
    <label>Continent Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
                <default>true</default>
                <label>Africa</label>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Profile__mdt/fields/Continent__c.field-meta.xml
<CustomField>
    <fullName>Continent__c</fullName>
    <label>Continent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
                <default>true</default>
                <label>Africa</label>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewCountriesClass.cls
public with sharing  class NewCountriesClass {
    
        public static void assignOwner(List<Lead> leadList){
            
            Set<String> countries = new Set<String>();
            
            for(Lead l :leadList){
                countries.add(l.country_name__c);
            }
            
            
            List<Country_Name__mdt> countriesContinent = new List<Country_Name__mdt>(
                [Select Label,Continent_Name__c from Country_Name__mdt Where Label IN :countries]
            );
            
            Map<String,String> countriesContinentMap = new Map<String,String>();
            
            for(Country_Name__mdt l :countriesContinent){
                countriesContinentMap.put(l.Label,l.Continent_Name__c);
            }
            
            List<Profile__mdt> Pro = new List<Profile__mdt>(
               [Select Label,Continent__c from Profile__mdt Where Continent__c In :countriesContinentMap.values()]
            );
            
            Map<String,String> proMap = new Map<String,String>();
            for(Profile__mdt l : Pro){
                proMap.put(l.Continent__c,l.Label);
            }
            
            List<User> userList = new List<User>(
                [Select Id,Name,UserName from User Where UserName In :proMap.values()]
            );
            
            Map<String,Id> newMaps = new Map<String,Id>();
            
            for(User l : userList){
                newMaps.put(l.userName,l.Id);
            }
            
            for(Lead l : leadList){
                if(countriesContinentMap.keySet().contains(l.country_name__c)){
                    /*String continent = countriesContinentMap.get(l.Country_Name__c);
                    String userName = proMap.get(continent);
                    String userId = newMaps.get(userName);
                    l.OwnerId = userId;*/
                    l.OwnerId = newMaps.get(proMAp.get(countriesContinentMap.get(l.Country_Name__c)));
                }
                else{
                    l.addError(l.country_name__c+' is not avilable for lead');
                }
            }
 
        }
}